# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Narakode
email: narakode@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Tempat belajar pemrograman gratis dengan materi yang lengkap
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.narakode.com" # the base hostname & protocol for your site, e.g. http://example.com
author: ibrahim

google_site_verification: UoFkVykNvEgzoez8SAkO7JcR82M_eDSYx55S_fdrQco

# Build settings
gems:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-timeago
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - mongocode.sublime-project

permalink: /:title

collections:
  pages:
    output: true
    permalink: /:name
  category:

pagination:
  enabled: true
  per_page: 6
  sort_reverse: true
  permalink: '/page/:num/'
  title: ':title - Page :num'
  trail:
    before: 2
    after: 2

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
